### ISSUE TITLE
`Network` peering status

### ISSUE THREAD

**Issue by afritzler** [ironcore-dev/metalnet#189]
# Summary

Do we currently have a way to determine the status of a `Network` peering? E.g. when a peering between two networks has been successful or failed? Currently the `Network` type has no peering related Status information.

**Comment by guvenc** [comment]
No, we dont have. This needs to be enhanced.

**Comment by kasabe28** [comment]
We can add this with below approach:
- Introduce `NetworkPeeringStatus` type with 2 fields:
  1. ID : peered network ID. It can be used by `metalnetlet` to sync peering status from metalnet.
  2. State: peering state will be either `Pending` or `Applied`
- while reconciling peered vnis of network, update the peering state based on subscription state.

**Comment by guvenc** [comment]
@kasabe28 I think `Applied` could be a bit misleading. (applied but is it ready ? ) 
Possible values `Ready`, `Pending` and `Error` sound better to me. (and conform to other object states in metalnet)
`ID` field sounds good.
